# Generated by Django 4.2.16 on 2025-03-09 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('done', models.BooleanField(default=False)),
                ('rem_time', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('qnno', models.IntegerField()),
                ('mark', models.IntegerField()),
                ('message', models.TextField()),
                ('timeofs', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission', to='app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('q1s', models.IntegerField(default=0)),
                ('q2s', models.IntegerField(default=0)),
                ('q3s', models.IntegerField(default=0)),
                ('q4s', models.IntegerField(default=0)),
                ('q5s', models.IntegerField(default=0)),
                ('q6s', models.IntegerField(default=0)),
                ('q7s', models.IntegerField(default=0)),
                ('q8s', models.IntegerField(default=0)),
                ('q1t', models.DecimalField(decimal_places=4, default=0.0, max_digits=14)),
                ('q2t', models.DecimalField(decimal_places=4, default=0.0, max_digits=14)),
                ('q3t', models.DecimalField(decimal_places=4, default=0.0, max_digits=14)),
                ('q4t', models.DecimalField(decimal_places=4, default=0.0, max_digits=14)),
                ('q5t', models.DecimalField(decimal_places=4, default=0.0, max_digits=14)),
                ('q6t', models.DecimalField(decimal_places=4, default=0.0, max_digits=14)),
                ('q7t', models.DecimalField(decimal_places=4, default=0.0, max_digits=14)),
                ('q8t', models.DecimalField(decimal_places=4, default=0.0, max_digits=14)),
                ('tot_score', models.IntegerField(default=0)),
                ('tot_time', models.DecimalField(decimal_places=4, default=0.0, max_digits=14)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='app.user')),
            ],
        ),
    ]
