# Generated by Django 5.1.7 on 2025-03-19 05:49

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('contact', models.CharField(max_length=100)),
                ('done', models.BooleanField(default=False)),
                ('rem_time', models.IntegerField(default=0)),
                ('groups', models.ManyToManyField(blank=True, related_name='participant_set', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='participant_set', to='auth.permission')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('q1s', models.IntegerField(default=0)),
                ('q2s', models.IntegerField(default=0)),
                ('q3s', models.IntegerField(default=0)),
                ('q4s', models.IntegerField(default=0)),
                ('q5s', models.IntegerField(default=0)),
                ('q6s', models.IntegerField(default=0)),
                ('q7s', models.IntegerField(default=0)),
                ('q8s', models.IntegerField(default=0)),
                ('q1t', models.DecimalField(decimal_places=4, default=0.0, max_digits=14)),
                ('q2t', models.DecimalField(decimal_places=4, default=0.0, max_digits=14)),
                ('q3t', models.DecimalField(decimal_places=4, default=0.0, max_digits=14)),
                ('q4t', models.DecimalField(decimal_places=4, default=0.0, max_digits=14)),
                ('q5t', models.DecimalField(decimal_places=4, default=0.0, max_digits=14)),
                ('q6t', models.DecimalField(decimal_places=4, default=0.0, max_digits=14)),
                ('q7t', models.DecimalField(decimal_places=4, default=0.0, max_digits=14)),
                ('q8t', models.DecimalField(decimal_places=4, default=0.0, max_digits=14)),
                ('tot_score', models.IntegerField(default=0)),
                ('tot_time', models.DecimalField(decimal_places=4, default=0.0, max_digits=14)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('qnno', models.IntegerField()),
                ('mark', models.IntegerField()),
                ('message', models.TextField()),
                ('timeofs', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
